name = "testings"
uuid = "bcc98c56-c950-4c80-b8c0-c89df4969d6d"
authors = ["momofor <mohammedaminechennofi@hotmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
